### ISSUE TITLE
Implement shipment

### ISSUE THREAD

**Issue by olimart** [shipppit/canada-post-api#1]
Work from `shipment` branch.
Add tests.

This is a fork from an exsisting gem for Canada Post API.
Currently it lets your retrieve shipping rates. The objective is to continue the work and implement shipment and label printing.

Shipment doc: https://www.canadapost.ca/cpo/mc/business/productsservices/developers/services/shippingmanifest/createshipment.jsf

XML schema:
https://www.canadapost.ca/cpo/mc/business/productsservices/developers/xsdfiles.jsf

Developer Doc.:
https://www.canadapost.ca/cpotools/apps/drc/home

Feel free to refer to the `active_shipping` gem should you need ruby code sample.

Your mission:
[from the list of rates available (see readme file)]
- Implement domestic (Canada) shipping
- Implement international shipping
- Print label (PDF and ZPLII)
- Provide addidtional documentation as per the process diagram (manifest, artifact...)
- Request refund

Globally speaking, keep the code modular (resource-oriented should we need to add more logic)

![shipping_workflow_3](https://cloud.githubusercontent.com/assets/547754/12045474/38e329a8-ae72-11e5-9f80-0287abe75912.jpg)

**Comment by olimart** [comment]
- the gem should use configured customer number but also accept an optional customer_number as params for MOBO (mail on behalf of) option.
- URL must be set based on mode
  - DRY `@credentials.mode == "production" ? PRODUCTION_URL : TEST_URL`
- Change command namespaces: `CanadaPost::Shipment.create` is easier to understand than `CANADA_POST_SERVICE.create`
- Default shipping_point to address_details[:zip] if not provided
- Set to false by default (if not already the case)
  - package.unpackaged
  - package.mailing_tube
- Notification: is it required or optional?
- Preferences: is it required or optional?
- replace `zip` by `postal_code`
- remove `xml.send(:'contract-id', '42708517')`. Feel free to default in development mode though

**Comment by nazrulcse** [comment]
1. It already in system. 
2. Done.
3. I know CanadaPost::Shipment.create it easier to understand, But `CANADA_POST_SERVICE` is the object of `CanadaPost::Shipment` and we pass the credential during initialize `CanadaPost::Shipment.new`. So I think it's OK.
4. Yeh, default `shipping_point` is sender zip code if not provide it. It's already in system.
5. Done
6. notification is required
7. Preferences is required
8. Done
9. Done

**Comment by olimart** [comment]
> It already in system.

can you document how to pass MOBO customer number and add test
- Can you move previous code under `rate` and move yours under `shipment`. Then, please remove `shipping`
