### ISSUE TITLE
Implement Authentication

### ISSUE THREAD

**Issue by olimart** [shipppit/canada-post-api#2]
Implement authentication process as per https://www.canadapost.ca/cpo/mc/business/productsservices/developers/services/ecomplatforms/default.jsf

Should retrieve a user object with information such as customer number. Return all attributes from the response.

**Comment by olimart** [comment]
As per this test file, registration on test environment seems to work.
Investigate why we can't make it work on our end with the test credentials.

[test_registration.html.zip](https://github.com/shipppit/shipppit-canada-post/files/163311/test_registration.html.zip)

**Comment by nazrulcse** [comment]
But we can't get the registration token by using sendbox credential

Do you have any sendbox credential?

**Comment by olimart** [comment]
yes, check the file attached. the token is '1111111111....'

**Comment by nazrulcse** [comment]
Yes, I have checked, But we can't test 

``` ruby
let(:registration) {
      canada_post_service.registration_token
    } 
```

By sendbox credential above

**Comment by olimart** [comment]
why not? what's the issue?

In sandbox, I get '1111111111111111111111' when calling `service.registratrion_token`

there are 2 things:
- get token
- send user to complete registration (which is currently my need)

**Comment by nazrulcse** [comment]
<HTTParty::Response:0xb870e78 parsed_response={"messages"=>{"message"=>{"code"=>"AA008", "description"=>"Only authorized platforms may access registration services."}}}, @response=#<Net::HTTPForbidden 403 Forbidden readbody=true>, @headers={"server"=>["Oracle-iPlanet-Web-Server/7.0"], "date"=>["Tue, 08 Mar 2016 16:10:07 GMT"], "x-backside-transport"=>["FAIL FAIL,FAIL FAIL"], "transfer-encoding"=>["chunked"], "content-type"=>["text/xml"], "www-authenticate"=>["default"], "x-client-ip"=>["10.229.109.82"], "x-global-transaction-id"=>["321283709"]}>
